"""Regenerate docs/MCP-TOOLS.md from the live MCP server definitions (so the reference never drifts)."""
import asyncio
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

from conftest import demo_overrides  # noqa: E402

from meridian.demo import write_context  # noqa: E402
from meridian.mcp_servers import SERVER_SCOPES  # noqa: E402
from meridian.runtime import Runtime  # noqa: E402

HEAD = """# MERIDIAN MCP tool reference

Generated by `python scripts/gen_mcp_docs.py` from the server definitions in `meridian/mcp_servers/`. Do not edit by hand.

## Endpoints and authentication

| Server | URL | Required scope |
| --- | --- | --- |
{rows}

* Transport: MCP streamable HTTP, stateless, JSON responses. Send `Authorization: Bearer <token>`.
* Token types:
  * agent token from `MERIDIAN_AGENT_TOKENS` (`name:token:scope+scope`);
  * console API key (scopes from its role);
  * OIDC / Entra JWT with audience `security.oidc.mcp_audience` (scopes from `security.mcp_scope_map`).
* Responses: 401 without a valid token, 403 when the server's scope is missing. Tool-level checks repeat the scope test, so in-process calls are held to the same rules.
* Every call is written to the audit chain as `tool:<name>` with the caller.
* Results that contain telemetry carry `"notice": "UNTRUSTED DATA ..."`. Clients must treat field values as data, never as instructions.
* Limits: at most 200 rows per call, a time window of at most 30 days per call, and at most 25 filter conditions.

## Query conditions (`where`)

Each condition is `{{"field": <column>, "op": <op>, "value": <value>}}`:

* `field` must be one of the columns returned by `describe_schema`.
* `op` is one of `eq`, `ne`, `in`, `not_in`, `contains`, `contains_any`, `startswith`, `endswith`, `gt`, `gte`, `lt`, `lte`, `is_null` or `not_null`.
* String comparisons are case-insensitive.
* Values are always bound as parameters, never spliced into SQL or KQL.

"""


def main() -> None:
    base = pathlib.Path(tempfile.mkdtemp())
    write_context(base / "context")
    rt = Runtime.load(None, **demo_overrides(base))
    rows = "\n".join(f"| {n} | `/mcp/{n}/` | `{'`, `'.join(sorted(s)) if isinstance(s, (set, list, tuple)) else s}` |"
                     for n, s in SERVER_SCOPES.items())
    out = [HEAD.format(rows=rows)]

    async def collect():
        for name, srv in rt.mcp_servers.items():
            out.append(f"## Server `{name}`\n")
            for t in await srv.list_tools():
                ann = t.annotations
                ro = bool(ann and ann.read_only_hint)
                out.append(f"### `{name}__{t.name}`\n")
                out.append(" ".join((t.description or "").split()) + "\n")
                out.append(f"Side effects: {'none (read-only)' if ro else 'writes (see description)'}\n")
                props = (t.input_schema or {}).get("properties", {})
                req = set((t.input_schema or {}).get("required", []))
                if props:
                    out.append("| Parameter | Type | Required | Default |\n| --- | --- | --- | --- |")
                    for p, spec in props.items():
                        typ = spec.get("type") or " / ".join(x.get("type", "?") for x in spec.get("anyOf", []))
                        out.append(f"| `{p}` | {typ} | {'yes' if p in req else 'no'} | {spec.get('default', '') if 'default' in spec else ''} |")
                    out.append("")
    asyncio.run(collect())
    (ROOT / "docs" / "MCP-TOOLS.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote docs/MCP-TOOLS.md")


if __name__ == "__main__":
    main()
