"""Regenerate the reference documents that are derived from code (so they never drift):

    docs/design/API-REFERENCE.md      REST + MCP endpoints with the role each requires
    docs/design/DATA-MODEL.md         OCSF-flat lake schema and operational store tables
    docs/design/ENVIRONMENT.md        every environment variable read by code or referenced by config

    python scripts/gen_reference_docs.py
"""
from __future__ import annotations

import inspect
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ.setdefault("MERIDIAN_NO_DOTENV", "1")
OUT = ROOT / "docs" / "design"
HEAD = "<!-- Generated by scripts/gen_reference_docs.py - do not edit by hand. -->\n\n"

ROUTE_NOTES = {
    "/healthz": ("none", "Liveness: the process is up. Used by container probes."),
    "/readyz": ("none", "Readiness: store reachable, rules loaded, no placeholder secrets; reports role heartbeats. 503 when not ready."),
    "/metrics": ("Bearer MERIDIAN_METRICS_TOKEN", "Prometheus metrics: work queue, cases, approvals, spend, heartbeats, per-source freshness."),
    "/login": ("none", "API-key sign-in form (GET) and key exchange for a session cookie (POST)."),
    "/logout": ("session", "Clears the session."),
    "/auth/login": ("none", "Starts OIDC sign-in (authorisation code + PKCE)."),
    "/auth/callback": ("none", "OIDC redirect URI; verifies the ID token and maps groups to a role."),
    "/": ("viewer", "Console: cases, approvals, alerts, runs."),
    "/cases/{case_id}": ("viewer", "Case page: timeline, notes, evidence, approvals."),
    "/api/ingest/{source}": ("HMAC MERIDIAN_INGEST_SECRET[_<SOURCE>]",
                             "Signed push into the landing zone: X-Meridian-Timestamp + X-Meridian-Signature over `ts.body`; 300 s window; 10 MB cap."),
    "/edl/{kind}.txt": ("Basic / Bearer MERIDIAN_EDL_TOKEN", "External dynamic list (`ip` or `domain`) pulled by firewalls and proxies."),
}


def api_reference() -> str:
    from meridian.api import app as m
    rows = []
    for r in m.app.routes:
        path = getattr(r, "path", None)
        methods = sorted((getattr(r, "methods", None) or set()) - {"HEAD"})
        ep = getattr(r, "endpoint", None)
        if not path or not methods or not ep:
            continue
        role, note = ROUTE_NOTES.get(path, ("", ""))
        try:
            src = inspect.getsource(ep)
            mm = re.search(r'need\("(\w+)"\)', src)
            if mm:
                role = mm.group(1)
        except (OSError, TypeError):
            pass
        doc = (ep.__doc__ or "").strip().split("\n")[0]
        rows.append(f"| {', '.join(methods)} | `{path}` | {role or '-'} | {note or doc or _describe(path)} |")
    body = "\n".join(rows)
    return HEAD + f"""# API reference

Roles are hierarchical: viewer < analyst < responder < admin. Authenticate with a session (SSO or API-key sign-in;
state-changing requests then need the `X-CSRF-Token` header equal to the `meridian_csrf` cookie), an `X-API-Key`
header, or `Authorization: Bearer <JWT>` from your IdP.

## HTTP endpoints

| Method | Path | Minimum role / auth | Purpose |
| --- | --- | --- | --- |
{body}

Interactive API documentation (`/docs`, `/redoc`, `/openapi.json`) is disabled unless `MERIDIAN_API_DOCS=1`.

## MCP endpoints

| Path | Required scope | Tools |
| --- | --- | --- |
| `/mcp/lake/` | `lake:read` | describe_schema, search_events, aggregate_events, entity_timeline, ioc_sweep |
| `/mcp/context/` | `context:read` | lookup_asset, lookup_identity, check_indicator, get_alert, related_alerts |
| `/mcp/cases/` | `cases:read` (+ `cases:write` for notes) | get_case, add_case_note |
| `/mcp/response/` | `response:request` | list_actions, request_containment (creates a pending approval only) |

Parameters and limits for every tool: [MCP-TOOLS.md](../MCP-TOOLS.md).

## Response codes used consistently

| Code | Meaning |
| --- | --- |
| 400 | Invalid input (validation message in `detail`) |
| 401 | Not authenticated |
| 403 | Authenticated but the role / scope is insufficient, CSRF token missing, or four-eyes violation |
| 404 | Not found |
| 409 | Approval no longer pending (already decided or expired) |
| 413 | Ingest body above 10 MB |
| 503 | Not ready (`/readyz`) |
"""


def _describe(path: str) -> str:
    return {
        "/api/me": "Current principal and role.",
        "/api/cases": "List cases (filter by status).",
        "/api/cases/{case_id}": "Case with alerts, notes and approvals.",
        "/api/cases/{case_id}/close": "Close a case with a verdict.",
        "/api/alerts": "List alerts (filter by status, rule).",
        "/api/approvals": "List approvals (pending by default).",
        "/api/approvals/{approval_id}/{decision}": "Approve or reject a containment request (four-eyes; executes once).",
        "/api/runs": "Agent runs with outcome, tokens, cost and degraded flag.",
        "/api/hunt/{hunt_id}": "Hunt status and result.",
        "/api/audit": "Recent audit entries and chain verification.",
    }.get(path, "")


def data_model() -> str:
    from meridian.ocsf import CLASSES, COLUMNS
    from meridian.store.db import md
    cols = "\n".join(f"| `{c}` | {str(t)} | {d} |" for c, (t, d) in COLUMNS.items())
    classes = "\n".join(f"| {k} | {v} |" for k, v in sorted(CLASSES.items()))
    tables = []
    for t in md.sorted_tables:
        rows = "\n".join(f"| `{c.name}` | {c.type} | {'PK' if c.primary_key else ''}{' idx' if c.index else ''} |"
                         for c in t.columns)
        tables.append(f"### `{t.name}`\n\n| Column | Type | Key |\n| --- | --- | --- |\n{rows}\n")
    return HEAD + f"""# Data model

## 1. Security data lake (OCSF-flat)

Every event becomes one row of a single wide, typed table. Files are Parquet (zstd), written under
`events/cls=<class_uid>/dt=<YYYY-MM-DD>/hr=<HH>/<batch-hash>.parquet` (UTC). `cls`, `dt` and `hr` are partition
columns used for pruning by DuckDB, Athena (partition projection) and the ADX ingestion mapping.

### OCSF classes

| class_uid | Class |
| --- | --- |
{classes}

### Columns

| Column | Arrow type | Meaning |
| --- | --- | --- |
{cols}

## 2. Operational store (PostgreSQL in production, SQLite for local use)

Tables are created at start-up if missing. Every string column except keys truncates at its declared length
(values come from attacker-controlled telemetry).

{chr(10).join(tables)}
## 3. State machines

### Alert

`new` -> (triage) -> `closed` (benign, auto-close gate passed) | `triaged` (kept for a human / joined to a case) |
`needs_human` (agent run failed or hit a limit)

### Case

`new` / `triaged` -> `investigating` -> `awaiting_approval` (containment requested) -> `contained` (action executed) -> `closed`;
a rejected request returns the case to `investigating`.

### Approval

`pending` -> `approved` -> `executed` | `failed`; or `pending` -> `rejected`; or `pending` -> `expired` (TTL,
default 24 h). The transition out of `pending` is atomic, so an approval executes at most once.

### Work item

`queued` -> `running` (leased, 3600 s for agents) -> `done` | `failed` (after max attempts) ; an expired lease
returns the item to the queue.
"""


def environment() -> str:
    found: dict[str, set[str]] = {}
    for p in (ROOT / "meridian").rglob("*.py"):
        for m in re.finditer(r'os\.environ(?:\.get)?[\(\[]\s*"([A-Z0-9_]+)', p.read_text()):
            found.setdefault(m.group(1), set()).add(str(p.relative_to(ROOT)))
    for p in (ROOT / "config").rglob("*.yaml"):
        for m in re.finditer(r"\$\{([A-Z0-9_]+)", p.read_text()):
            if m.group(1) != "ENV_VAR":
                found.setdefault(m.group(1), set()).add(str(p.relative_to(ROOT)))
    secret = re.compile(r"(KEY|SECRET|TOKEN|PASSWORD|CREDENTIALS|DATABASE_URL)")
    rows = "\n".join(f"| `{k}` | {'yes' if secret.search(k) else ''} | {', '.join(sorted(v))} |" for k, v in sorted(found.items()))
    return HEAD + f"""# Environment variables

Secrets (marked) come from Key Vault (Azure) or Secrets Manager (AWS) in the cloud deployments and from a git-ignored
`.env` locally. Configuration files only ever reference them as `${{VAR}}`; the loader refuses literal secrets.

| Variable | Secret | Read by |
| --- | --- | --- |
{rows}
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, fn in (("API-REFERENCE.md", api_reference), ("DATA-MODEL.md", data_model), ("ENVIRONMENT.md", environment)):
        (OUT / name).write_text(fn(), encoding="utf-8")
        print("wrote docs/design/" + name)


if __name__ == "__main__":
    main()
